### ISSUE TITLE
/entrypoint.sh: exec: line 25: /usr/bin/php-fpm: not found

### ISSUE THREAD

**Issue by typia** [ptman/racktables-docker#2]
Hi,
I accidentally upgraded to latest version and now the container is not starting stating 👍 

/entrypoint.sh: exec: line 25: /usr/bin/php-fpm: not found
To initialize the db, first go to /?module=installer&step=5

My db is in place.

Could you please help ?

**Comment by ptman** [comment]
Hi,

Apprently Alpine Linux 3.6 renamed some of the PHP binaries. Hopefully d7a35dbcd14ffccac8cd2029dd6f97311f41979e fixes this for you

**Comment by typia** [comment]
Hi,
indeed it fixed it.

Many Thanks

**Comment by typia** [comment]
Hi,
indeed it fixed it.

Many thanks
