### ISSUE TITLE
Help starting racktables

### ISSUE THREAD

**Issue by matt32106** [ptman/racktables-docker#3]
Hi, (warning: docker noob speaking)
I installed "docker toolbox" on my win7 box.
Then:
```
$ docker run -d ptman/racktables
$ docker container ls
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f790ad1761ed        ptman/racktables    "/entrypoint.sh /usr"   4 seconds ago       Up 3 seconds        9000/tcp            agitated_pare
$ docker-machine ip
192.168.99.100
```

I then try to access 192.168.99.100 in firefox but it throws a connexion error, 192.168.99.100:9000, same error.

I then used nmap from the win7 box on 192.168.99.100 and it tells me that ports 22 and 2376 are opened (ssh and docker presumably), but I see no www.

I assume I have to run something on the docker container but what and how?

**Comment by ptman** [comment]
Did you read the README? docker-compose has more relevant information. I'm not really maintaining this actively anymore.

**Comment by matt32106** [comment]
Ok, thanks for reading.
I had more luck with planet/docker-racktables so I close this issue.
Regards
